/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
//Thread mode
void generate_interrupt(void){
	uint32_t *pSTIR = (uint32_t*) 0xE000EF00;
	uint32_t *pISER0 = (uint32_t*) 0xE000E100;

	*pISER0 |=	(1<<3);
	*pSTIR	|=	(3& 0x1FE);
}

void change_access_level_unpri(void){
	//read
	__asm volatile ("MRS R0,CONTROL");
	//write
	__asm volatile ("ORR R0,R0,#0x01");
	//modify
	__asm volatile ("MSR CONTROL,R0");
}

// starts with thread mode and privileged access levels
int main(void)
{
	printf("In thread mode : before interrupt\n");
	change_access_level_unpri();
	generate_interrupt();
	printf("In thread mode : after interrupt\n");
	for(;;); // need to continue
}

void RTC_WKUP_IRQHandler(void){
	printf("In handler mode : ISR\n");
}

void HardFault_Handler(void){
	printf("Hard fault detected\n");
	while(1);
}
