/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

void generate_interrupt(){
	uint32_t *pSTIR = (uint32_t*) 0xE000EF00;
	uint32_t *pISER0 = (uint32_t*) 0xE000E100;

	*pISER0 |=	(1<<3);
	*pSTIR	|=	(3& 0x1FE);
}

int main(void)
{
	printf("In thread mode : before interrupt\n");
	generate_interrupt();
	printf("In thread mode : after interrupt\n");
	for(;;); // need to continue
}

void RTC_WKUP_IRQHandler(void){
	printf("In handler mode : ISR\n");
}
